//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        public string 課號 { get; set; }
        public string 課名 { get; set; }
        public int 學分數 { get; set; }
        public string 上課地點 { get; set; }
        public string 講師名字 { get; set; }
    }
}
