//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public string 學號 { get; set; }
        public string 姓名 { get; set; }
        public DateTime 生日 { get; set; }
        public string Email { get; set; }
    }
}
